config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :memberships
  resources :beer_clubs
  resources :users
  resources :beers
  resources :breweries

  resources :breweries do
    post 'toggle_activity', on: :member
  end

  resources :users do
    post 'toggle_activity', on: :member
  end

  resources :memberships do
    post 'toggle_activity', on: :member
  end

  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  resources :places, only:[:index, :show]
  post 'places', to:'places#search'
  get 'beerlist', to:'beers#list'
  get 'ngbeerlist', to:'beers#nglist'
  get 'ngbrewerylist', to:'breweries#nglist'

  get 'auth/:provider/callback', to: 'sessions#create_oauth'

  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]

end

app/models/brewery.rb
class Brewery < ActiveRecord::Base
  include RatingAverage

  validates :name, presence: true
  validates :year, numericality: { less_than_or_equal_to: Proc.new { Time.now.year } }

  scope :active, -> { where active:true }
  scope :retired, -> { where active:[nil,false] }

  has_many :beers, dependent: :destroy
  has_many :ratings, through: :beers

  def self.top(n)
    sorted_by_rating_average = Brewery.all.sort_by{ |b| -(b.average_rating || 0) }
    sorted_by_rating_average[0, n]
  end
end

app/controllers/breweries_controller.rb
class BreweriesController < ApplicationController
  before_action :set_brewery, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :nglist]
  before_action :ensure_that_current_user_is_admin, only: [:destroy]
  before_action :skip_if_cached, only:[:index]

  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if fragment_exist?( "brewerylist-#{@order}"  )
  end

  # GET /breweries
  # GET /breweries.json
  def index
    #@breweries = Brewery.all
    @active_breweries = Brewery.active
    @retired_breweries = Brewery.retired

    @active_breweries = case @order
                          when 'name' then
                            @active_breweries.sort_by { |b| b.name }
                          when 'year' then
                            @active_breweries.sort_by { |b| b.year }
                          when '-name' then
                            @active_breweries.sort_by { |b| b.name }.reverse
                          when '-year' then
                            @active_breweries.sort_by { |b| -b.year }
                        end

    @retired_breweries = case @order
                           when 'name' then
                             @retired_breweries.sort_by { |b| b.name }
                           when 'year' then
                             @retired_breweries.sort_by { |b| b.year }
                           when '-name' then
                             @retired_breweries.sort_by { |b| b.name }.reverse
                           when '-year' then
                             @retired_breweries.sort_by { |b| -b.year }
                         end
  end

  # GET /breweries/1
  # GET /breweries/1.json
  def show
  end

  # GET /breweries/new
  def new
    @brewery = Brewery.new
  end

  # GET /breweries/1/edit
  def edit
  end

  # POST /breweries
  # POST /breweries.json
  def create
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    @brewery = Brewery.new(brewery_params)

    respond_to do |format|
      if @brewery.save
        format.html { redirect_to @brewery, notice: 'Brewery was successfully created.' }
        format.json { render :show, status: :created, location: @brewery }
      else
        format.html { render :new }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /breweries/1
  # PATCH/PUT /breweries/1.json
  def update
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    respond_to do |format|
      if @brewery.update(brewery_params)
        format.html { redirect_to @brewery, notice: 'Brewery was successfully updated.' }
        format.json { render :show, status: :ok, location: @brewery }
      else
        format.html { render :edit }
        format.json { render json: @brewery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /breweries/1
  # DELETE /breweries/1.json
  def destroy
    ["brewerylist-name", "brewerylist-year"].each{ |f| expire_fragment(f) }
    @brewery.destroy
    respond_to do |format|
      format.html { redirect_to breweries_url, notice: 'Brewery was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def toggle_activity
    brewery = Brewery.find(params[:id])
    brewery.update_attribute :active, (not brewery.active)

    new_status = brewery.active? ? "active" : "retired"

    redirect_to :back, notice: "brewery activity status changed to #{new_status}"
  end

  def nglist

  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_brewery
    @brewery = Brewery.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def brewery_params
    params.require(:brewery).permit(:name, :year, :active)
  end
end

app/helpers/breweries_helper.rb
module BreweriesHelper
end

app/views/breweries/_form.html.erb
<%= form_for(@brewery) do |f| %>
  <% if @brewery.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@brewery.errors.count, "error") %> prohibited this brewery from being saved:</h2>

      <ul>
      <% @brewery.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :active %>
    <%= f.check_box :active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/breweries/_list.html.erb
<% cache "brewerylist-#{@order}", skip_digest: true do %>

    <table class="table table-hover">
      <thead>
      <tr>
        <th>
          <% if session[:order] != 'name' %>
              <%= link_to 'Name', breweries_path(order: "name") %>
          <% else %>
              <%= link_to 'Name', breweries_path(order: "-name") %>
          <% end %>
        </th>
        <th>
          <% if session[:order] != 'year' %>
              <%= link_to 'Year', breweries_path(order: "year") %>
          <% else %>
              <%= link_to 'Year', breweries_path(order: "-year") %>
          <% end %>
        </th>
      </tr>
      </thead>

      <tbody>
      <% breweries.each do |brewery| %>
          <tr>
            <td><%= link_to brewery.name, brewery %></td>
            <td><%= brewery.year %></td>
            <td></td>
          </tr>
      <% end %>
      </tbody>
    </table>

<% end %>

app/views/breweries/edit.html.erb
<h1>Editing Brewery</h1>

<%= render 'form' %>

<%= link_to 'Show', @brewery %> |
<%= link_to 'Back', breweries_path %>

app/views/breweries/index.html.erb
<h1>Breweries</h1>

<h2>Active</h2>




<%= render 'list', breweries: @active_breweries %>

<h2>Retired</h2>


<%= render 'list', breweries: @retired_breweries %>


<br>

<%= link_to 'New Brewery', new_brewery_path, class: "btn btn-primary" %>

app/views/breweries/new.html.erb
<h1>New Brewery</h1>

<%= render 'form' %>

<%= link_to 'Back', breweries_path %>

app/views/breweries/nglist.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/angular.js/1.4.5/angular.min.js"></script>
<script>
  var myApp = angular.module('myApp', []);

  myApp.controller("BreweriesController", function ($scope, $http) {
    $http.get('breweries.json').success( function(data, status, headers, config) {
      $scope.breweries = data;
    });

    $scope.order = 'name';

    $scope.sort_by = function (order){
      $scope.order = order;
      console.log(order);
    }
  });
</script>

<h2>Breweries</h2>

<div ng-app="myApp" ng-controller="BreweriesController">

  <table class="table table-hover">
    <thead>
    <th> <a ng-click="sort_by('name')">name</a> </th>
    <th> <a ng-click="sort_by('year')">year</a> </th>
    <th> <a ng-click="sort_by('beers')">number of beers</a> </th>
    </thead>
    <tr ng-repeat="brewery in breweries| orderBy:order">
      <td>{{brewery.name}}</td>
      <td>{{brewery.year}}</td>
      <td>{{brewery.beers.length}}</td>
    </tr>
  </table>

</div>

app/views/breweries/show.html.erb
<% cache @brewery do %>

    <h2><%= @brewery.name %>
      <% if not @brewery.active %>
          <span class="label label-info">retired</span>
      <% end %>
    </h2>

    <em>
      Established at
      <%= @brewery.year %>
    </em>

    <p>
      Number of beers
      <%= @brewery.beers.count %>
    </p>

    <p>
      <% @brewery.beers.each do |beer| %>
          <%= link_to beer.name, beer %>
      <% end %>
    </p>

    <p>
      <% if @brewery.ratings.empty? %>
          brewery has no ratings
      <% else %>
          brewery has <%= pluralize(@brewery.ratings.count, 'rating') %>, average <%= round(@brewery.average_rating) %>
      <% end %>
    </p>
<% end %>

<%= edit_and_destroy_buttons(@brewery) %>

<%= link_to "change activity", toggle_activity_brewery_path(@brewery.id), method: :post, class: "btn btn-primary" if current_user %>